name: Deploy to Staging

run-name: Staging Deploy Branch ${{ github.ref_name }} by @${{ github.actor }}

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Nodejs 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn install

      - name: Build App
        run: yarn build-staging

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy static site to S3 bucket
        run: |
          aws s3 sync ./dist s3://${{ secrets.AWS_STORAGE_BUCKET_NAME }} --delete